### ISSUE TITLE
EditHost解析hosts时碰到空行报错

### ISSUE THREAD

**Issue by bnpzsx** [QPT-Family/QWebSiteOptimizer#1]
![image](https://user-images.githubusercontent.com/22561030/132847521-7bd87331-bae7-4b10-9f1b-3966478ccf7c.png)
此时line = ['']

**Comment by GT-ZhangAcer** [comment]
应该是...修好了，晚上回家再试一下 哈哈哈，等发版了我也会再测一次

**Comment by GT-ZhangAcer** [comment]
已经发版啦，大佬如果需要的话可以试试最新的V0.9版本，或者[点击下载Windows](https://bj.bcebos.com/v1/ai-studio-online/0fbc4cfccb3f42139bfd98bf976298d5c64664bd1981442081d8177a8609d24a?responseContentDisposition=attachment%3B%20filename%3DGitHub%E5%8A%A0%E9%80%9F%E5%B7%A5%E5%85%B7V0.9.zip)直接用也成~
